server:
#  port: 8088
  servlet:
    context-path: /ticNews

spring:
  application.name: ticNews
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tic?zeroDateTimeBehavior=convertToNull&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    show-sql: true