server:
#  port: 8080
  servlet:
    context-path: /ticNews

spring:
  application.name: ticNews
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jianbao?zeroDateTimeBehavior=convertToNull&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
  cache:
    type: ehcache
    ehcache:
      config: classpath:cache/ehcache.xml
wx:
  push: true
  appId: pleaseinput
  appKey: pleaseinput
  templateId: fXvHklP1K8DCTO7p-h2wfscB6cnFSpF9pW6k5TF-AI0
  token:
  xiaochengxu:
    appId:
    appSecret: